nodeLinker: node-modules

npmRegistries:
  'https://npm.pkg.github.com/playht':
    npmAuthToken: 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

npmScopes:
  playht:
    npmRegistryServer: 'https://npm.pkg.github.com/playht'

yarnPath: .yarn/releases/yarn-3.6.2.cjs
