nodeLinker: node-modules

npmRegistries:
  'https://npm.pkg.github.com/playht':
    npmAuthToken: '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'

npmScopes:
  playht:
    npmRegistryServer: 'https://npm.pkg.github.com/playht'
